// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9hvkJfyi3CbJeXeN8vJ29C0awk6d86yw',
    appId: '1:450481104774:web:024f587a07ed3dbec3ee07',
    messagingSenderId: '450481104774',
    projectId: 'unasplash-38796',
    authDomain: 'unasplash-38796.firebaseapp.com',
    storageBucket: 'unasplash-38796.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Xl6r0FdA8WLeex13tVmr1B0dcRgrkx8',
    appId: '1:450481104774:android:daa398f9e29242d5c3ee07',
    messagingSenderId: '450481104774',
    projectId: 'unasplash-38796',
    storageBucket: 'unasplash-38796.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDluj3Tvr2hofPJ51m_J0FK6F_A9HozscQ',
    appId: '1:450481104774:ios:8e925d9428784eb8c3ee07',
    messagingSenderId: '450481104774',
    projectId: 'unasplash-38796',
    storageBucket: 'unasplash-38796.appspot.com',
    iosBundleId: 'com.example.unasplash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDluj3Tvr2hofPJ51m_J0FK6F_A9HozscQ',
    appId: '1:450481104774:ios:ac5ae336adf5388dc3ee07',
    messagingSenderId: '450481104774',
    projectId: 'unasplash-38796',
    storageBucket: 'unasplash-38796.appspot.com',
    iosBundleId: 'com.example.unasplash.RunnerTests',
  );
}
